language: c++

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - wget -O cmake.sh https://cmake.org/files/v3.17/cmake-3.17.5-Linux-x86_64.sh
  - sudo mkdir /usr/local/cmake-3.17.5
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local/cmake-3.17.5
  - export PATH=/usr/local/cmake-3.17.5/bin:$PATH
  - sudo apt-get -y install gfortran
  - sudo apt-get -y install valgrind
  - sudo apt-get -y install ninja-build

install:
  - cd ..
  - mkdir tribits-build
  - cd tribits-build

script:
  - which cmake
  - cmake --version
  - ctest -V -S ../TriBITS/cmake/ctest/travisci/ctest_trusty_serial_debug.cmake
